version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '[%(asctime)s] [%(levelname)s] %(name)s.%(funcName)s: %(message)s'
  
  console_format:
    format: '[%(asctime)s] %(funcName)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_format
    stream: ext://sys.stdout

  app_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/app.log
    maxBytes: 1048576 
    backupCount: 5
    encoding: utf8

  process_video_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/process_video.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  ffmpeg_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/ffmpeg.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  pipeline_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/pipeline.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  analysis_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/analysis.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  file_utils_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/file_utils.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  uvicorn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: api/logs/logs/uvicorn.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  file_routes_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/file_routes.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

  processing_routes_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: api/logs/logs/processing_routes.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8

loggers:

  process_video:
    handlers: [process_video_file_handler, console, app_file_handler]  
    level: DEBUG
    propagate: false

  multipart:
    handlers: [app_file_handler]  
    level: WARNING
    propagate: false

  ffmpeg_logger:
    handlers: [ffmpeg_file_handler]
    level: DEBUG
    propagate: false

  pipeline_logger:
    handlers: [pipeline_file_handler, console, app_file_handler]
    level: DEBUG
    propagate: false

  analysis_logger:
    handlers: [analysis_file_handler, console, app_file_handler]
    level: DEBUG
    propagate: false

  file_utils_logger:
    handlers: [file_utils_file_handler, console, app_file_handler]
    level: DEBUG
    propagate: false

  api_logger:
    handlers: [console, app_file_handler]
    level: DEBUG
    propagate: false

  fastapi:
    handlers: [console, app_file_handler]
    level: DEBUG
    propagate: false

  uvicorn:
    handlers: [uvicorn_file_handler, console, app_file_handler]
    level: INFO
    propagate: false

  uvicorn.error:
    handlers: [uvicorn_file_handler, console, app_file_handler]
    level: ERROR
    propagate: false

  uvicorn.access:
    handlers: [uvicorn_file_handler, console, app_file_handler]
    level: INFO
    propagate: false

  file_routes:
    handlers: [file_routes_file_handler, console, app_file_handler]
    level: DEBUG
    propagate: false

  processing_routes:
    handlers: [processing_routes_file_handler, console, app_file_handler]
    level: DEBUG
    propagate: false

  asyncio:
    level: WARNING
    propagate: false

root:
  handlers: [app_file_handler, console]
  level: DEBUG
