from typing_extensions import Final
from typing import List
from api.config.settings import (
    LOGS_BASE, LOGS_DIR, FINAL_LOGS_DIR, RUN_LOGS_DIR, LOG_CONFIG_PATH,
    FILE_HANDLING_DIR, TEMP_PROCESSING_DIR, FINAL_OUTPUT_DIR, DATA_WORK_PYAVI_DIR,
    DATA_WORK_DIR, DATA_DIR, DEFAULT_MAX_ITERATIONS, TEST_DATA_DIR,
    ALLOWED_LOCAL_1, ALLOWED_LOCAL_2, ALLOWED_ORIGINS
)

# Logging directories
LOGS_BASE: Final[str] = LOGS_BASE
LOGS_DIR: Final[str] = LOGS_DIR
FINAL_LOGS_DIR: Final[str] = FINAL_LOGS_DIR
RUN_LOGS_DIR: Final[str] = RUN_LOGS_DIR
LOG_CONFIG_PATH: Final[str] = LOG_CONFIG_PATH

# Processing directories
FILE_HANDLING_DIR: Final[str] = FILE_HANDLING_DIR
TEMP_PROCESSING_DIR: Final[str] = TEMP_PROCESSING_DIR
FINAL_OUTPUT_DIR: Final[str] = FINAL_OUTPUT_DIR
DATA_WORK_PYAVI_DIR: Final[str] = DATA_WORK_PYAVI_DIR
DATA_WORK_DIR: Final[str] = DATA_WORK_DIR
DATA_DIR: Final[str] = DATA_DIR

# Processing constants
DEFAULT_MAX_ITERATIONS: Final[int] = DEFAULT_MAX_ITERATIONS

# Test data directory
TEST_DATA_DIR: Final[str] = TEST_DATA_DIR

# Allowed CORS origins
ALLOWED_LOCAL_1: Final[str] = ALLOWED_LOCAL_1
ALLOWED_LOCAL_2: Final[str] = ALLOWED_LOCAL_2
ALLOWED_ORIGINS: Final[List[str]] = ALLOWED_ORIGINS
