name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04 

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set PYTHONPATH to repository root
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: CI build test and breakdown ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r syncnet_python/requirements.txt

    - name: Make download_model.sh executable
      run: |
        chmod +x ./download_model.sh

    - name: Run download_model.sh
      run: |
        echo "=== Executing download_model.sh ==="
        ./download_model.sh
        echo "=== Finished executing download_model.sh ==="

    - name: Test SyncNet Execution
      run: |
        echo "=== Testing SyncNet Execution ==="
        python -m syncnet_python.run_pipeline --videofile syncnet_python/data/example.avi --reference 00001
        python -m syncnet_python.run_syncnet --videofile syncnet_python/data/example.avi --reference 00001
      continue-on-error: true 

    - name: Run Unit Tests
      run: |
        echo "=== Starting Unit Tests ==="
        python3.7 -m unittest discover -s api/tests/test_utils -p "*.py" -v
        echo "=== Completed Unit Tests ==="

    - name: Run Integration Tests
      run: |
        echo "=== Starting Integration Tests ==="
        python3.7 -m unittest discover -s api/tests -p "*.py" -v
        echo "=== Completed Integration Tests ==="
