name: Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04  # Changed to ubuntu-22.04 for better Python 3.7 support

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Caches pip dependencies

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r syncnet_python/requirements.txt

    # 4. Make download_model.sh executable
    - name: Make download_model.sh executable
      run: |
        chmod +x ./download_model.sh

    # 5. Run download_model.sh script
    - name: Run download_model.sh
      run: |
        ./download_model.sh

    # 6. Run unit tests
    - name: Run unit tests
      run: |
        python3.7 -m unittest discover -s syncnet_python/tests/test_utils -p "*.py" -v

